### ISSUE TITLE
Organize JS, CSS, and HTML files into their own folder

### ISSUE THREAD

**Issue by RyanRussell00** [FabioCentrella94/project5#31]
Make a folder called: scripts and put all the back-end JS code in there.
Make a folder called: tests and put all the JS tests in there
Make a folder called: pages and put all the HTML files in there. (DO NOT PUT INDEX.HTML THERE)
Make a folder called: styles and put all the CSS files in there

**Comment by FabioCentrella94** [comment]
Hi Ryan,

In the ’scripts’ folder I should move the javascript file I created for the project or the ones already existing when I forked the the repository from Openclassroom?

Regards,
Fabio
